name: Android Release Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PACKAGE_NAME: "com.budgetwisebare"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install dependencies
        run: npm install

      - name: Inject fallback autolinking.json
        run: |
          mkdir -p android/build/generated/autolinking
          echo '{"modules":[],"targets":[]}' > android/build/generated/autolinking/autolinking.json

      - name: Override react-native config
        run: |
          echo '{
            "project": {
              "android": {
                "packageName": "com.budgetwisebare"
              }
            }
          }' > config-output.json
          mkdir -p node_modules/.bin
          echo '#!/bin/bash' > node_modules/.bin/react-native
          echo 'if [[ "$1" == "config" ]]; then cat config-output.json; else npx react-native "$@"; fi' >> node_modules/.bin/react-native
          chmod +x node_modules/.bin/react-native

      - name: Build Android release APK
        run: |
          export PATH=$(pwd)/node_modules/.bin:$PATH
          cd android
          chmod +x ./gradlew
          ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: android/app/build/outputs/apk/release/*.apk
